spring: 
  application:
    name: locaquest
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  redis:
    host: ${SPRING_REDIS_URL}
    port: ${SPRING_REDIS_PORT}
    timeout: ${SPRING_REDIS_TIMEOUT}
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BROKERS}
    consumer:
      group-id: my-consumer-group
      auto-offset-reset: earliest
      enable-auto-commit: false
    producer:
      acks: all
      retries: 3
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    listener:
      ack-mode: manual
logging:
  level:
    org.springframework: OFF
    org.springframework.web: OFF
    org.springframework.kafka: warn
    org.hibernate: OFF
    org.apache: OFF
    org.apache.catalina: OFF
    com.zaxxer: OFF
email:
  providers:
    - domain: gmail.com
      providerName: Gmail
      smtpHost: smtp.gmail.com
      smtpPort: 587
    - domain: outlook.com
      providerName: Outlook
      smtpHost: smtp-mail.outlook.com
      smtpPort: 587
    - domain: yahoo.com
      providerName: Yahoo
      smtpHost: smtp.mail.yahoo.com
      smtpPort: 587
    - domain: naver.com
      providerName: Naver
      smtpHost: smtp.naver.com
      smtpPort: 587
jwt:
  key:
    login: ${SPRING_JWT_KEY_LOGIN}
    auth: ${SPRING_JWT_KEY_AUTH}
  expiration:
    access: ${SPRING_JWT_EXPIRATION_ACCESS}
    refresh: ${SPRING_JWT_REFRESH_ACCESS}
    auth: ${SPRING_JWT_VERIFICATION_ACCESS}
google:
  key: ${GOOGLE_PLACE_API_KEY}
kafka:
  topic:
    user-param-gain: ${SPRING_KAFKA_TOPIC_USER_PARAM_GAIN}
